### ISSUE TITLE
Python 3.10 SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by amaanq** [Galaxy1036/pylzham#5]
I believe the PY_SSIZE_T_CLEAN macro has to be defined for Python 3.10 onwards, which is simply done with #define PY_SSIZE_T_CLEAN above #include <Python.h> 

I fixed this in my fork, but a fix on your end would be awesome :)

**Comment by Galaxy1036** [comment]
Should be fixed in the following [commit](https://github.com/Galaxy1036/pylzham/commit/cf0df606b430117297d28ca0f89a0b7ec8fb3e6d).
